// Plan view — Content Calendar
import { getCalendar } from "@/lib/sheets";
import { Card } from "@/components/Card";
import PageHeader from "@/components/PageHeader";

export const dynamic = "force-dynamic";
export const revalidate = 300;

const formatColors: Record<string, { bg: string; text: string }> = {
  Reel:     { bg: "bg-pink-50",    text: "text-pink-700" },
  Photo:    { bg: "bg-blue-50",    text: "text-blue-700" },
  Carousel: { bg: "bg-amber-50",   text: "text-amber-700" },
  Video:    { bg: "bg-purple-50",  text: "text-purple-700" },
  Link:     { bg: "bg-teal-50",    text: "text-teal-700" },
  Status:   { bg: "bg-slate-100",  text: "text-slate-700" },
};

export default async function PlanPage() {
  const calendar = await getCalendar();
  const byDay: Record<string, typeof calendar> = {};
  for (const slot of calendar) {
    (byDay[slot.day] = byDay[slot.day] || []).push(slot);
  }
  const daysOrder = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
  const orderedDays = daysOrder.filter((d) => byDay[d]?.length);

  return (
    <div>
      <PageHeader title="Plan" subtitle="Next week's content calendar with briefs" dateLabel="Generated by latest weekly run" showPicker={false} />

      {calendar.length === 0 && (
        <Card className="text-center py-12">
          <p className="text-slate-700 font-medium">No calendar generated yet</p>
          <p className="text-slate-500 text-sm mt-2">The next weekly pipeline run will populate next week's plan.</p>
        </Card>
      )}

      <div className="space-y-3">
        {orderedDays.map((day) => {
          const slots = byDay[day];
          return (
            <Card key={day} className="!p-0 overflow-hidden">
              <div className="px-6 py-3 bg-slate-50 border-b border-slate-200 flex items-center justify-between">
                <div>
                  <div className="font-semibold text-slate-900">{day}</div>
                  <div className="text-xs text-slate-500">{slots[0]?.date}</div>
                </div>
                <div className="text-xs text-slate-500">{slots.length} posts</div>
              </div>
              <div className="divide-y divide-slate-100">
                {slots.map((slot, i) => {
                  const fc = formatColors[slot.format] || formatColors.Status;
                  return (
                    <div key={i} className="px-6 py-4">
                      <div className="flex items-start gap-3">
                        <div className="flex-shrink-0 w-16 text-sm font-medium text-slate-700">{slot.time_bdt || "—"}</div>
                        <div className="flex-shrink-0">
                          <span className={`text-[11px] font-semibold px-2 py-0.5 rounded ${fc.bg} ${fc.text}`}>
                            {slot.format}
                          </span>
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="text-xs text-slate-500 mb-1.5">
                            {slot.pillar}
                            {(slot.spotlight_name || (slot.featured_entity && slot.featured_entity !== "None")) && (
                              <span> · <span className="text-slate-600">
                                {slot.spotlight_name || slot.featured_entity}
                                {slot.spotlight_type && slot.spotlight_type !== "None" && (
                                  <span className="text-slate-400"> ({slot.spotlight_type})</span>
                                )}
                              </span></span>
                            )}
                            {slot.audience && <span> · {slot.audience}</span>}
                          </div>
                          <div className="text-[15px] text-slate-900 font-medium leading-snug">{slot.hook_line}</div>
                          {slot.key_message && <div className="text-sm text-slate-600 mt-1">{slot.key_message}</div>}
                          {slot.visual_direction && (
                            <div className="text-xs text-slate-500 mt-2">
                              <span className="text-slate-700 font-medium">Visual: </span>{slot.visual_direction}
                            </div>
                          )}
                          <div className="text-xs text-slate-500 mt-1.5">
                            <span className="text-slate-700 font-medium">CTA: </span>{slot.cta}
                          </div>
                          <div className="flex flex-wrap gap-x-4 gap-y-1 mt-2 text-xs text-slate-500">
                            {slot.expected_reach && (<span><span className="text-slate-700">Expected: </span>{slot.expected_reach}</span>)}
                            {slot.success_metric && (<span><span className="text-slate-700">Success: </span>{slot.success_metric}</span>)}
                          </div>
                          {slot.rationale && (
                            <details className="mt-2">
                              <summary className="text-xs text-slate-500 cursor-pointer hover:text-slate-800">Rationale</summary>
                              <div className="mt-1.5 text-xs text-slate-600 bg-slate-50 rounded p-2">{slot.rationale}</div>
                            </details>
                          )}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </Card>
          );
        })}
      </div>

      <div className="text-center text-xs text-slate-400 py-6">Edit slots in the Content_Calendar tab of the Google Sheet. Changes reflect here within 5 minutes.</div>
    </div>
  );
}
